from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DashboardActionContract:
    contract_id: str
    label: str
    view: str
    trigger: str
    action_kind: str | None
    approval: str
    scope: str
    cluster: str
    writes: tuple[str, ...]
    prerequisites: tuple[str, ...]
    postcondition: str
    safer_option: str
    recovery: str
    metadata_keys: tuple[str, ...] = ()
    output_suffixes: tuple[str, ...] = ()
    mode: str = "action"


DASHBOARD_ACTION_CONTRACTS: dict[str, DashboardActionContract] = {
    "md-slate-rehearsal": DashboardActionContract(
        contract_id="md-slate-rehearsal",
        label="Rehearse selected MD slate",
        view="Peptides",
        trigger="Run rehearsal for selected MD slate",
        action_kind="md-slate-rehearsal",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("dashboard-local MD slate rehearsal state", "dashboard-local fake campaign evidence"),
        prerequisites=("At least one launch-ready candidate with a source batch CSV",),
        postcondition="A rehearsal slate finishes locally and reports review-ready/blocked outcomes without touching BURA.",
        safer_option="This action is already the safer option; it never launches real remote work.",
        recovery="Inspect MD Validation -> Slate monitor, then launch the real slate only if the rehearsal path looks healthy.",
    ),
    "md-slate-run": DashboardActionContract(
        contract_id="md-slate-run",
        label="Launch GUI-managed MD slate",
        view="Peptides",
        trigger="Launch selected MD slate",
        action_kind="md-slate-run",
        approval="required",
        scope="bura",
        cluster="bura",
        writes=("dashboard action draft", "dashboard-local MD slate state"),
        prerequisites=("Selected peptides are launch-ready", "BURA profile is configured", "local cap simulation is acceptable"),
        postcondition="A single approval-gated supervisory slate is created and later schedules per-peptide MD child actions.",
        safer_option="Run the MD slate rehearsal first to dry-run the same ladder logic locally.",
        recovery="Pause the slate or use the Recovery center if a peptide blocks or drifts.",
        metadata_keys=("slate_id", "peptide_count"),
    ),
    "prepare-md-stage": DashboardActionContract(
        contract_id="prepare-md-stage",
        label="Prepare next MD stage locally",
        view="MD Validation",
        trigger="Advance ladder plan: Prepare ...",
        action_kind="prepare-md-stage",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("local campaign directory", "manifest/stage metadata"),
        prerequisites=("A source batch CSV exists", "the next stage is selected"),
        postcondition="A local campaign package is created and becomes ready for BURA staging.",
        safer_option="Use the MD slate rehearsal when you want to test the ladder flow without a real campaign.",
        recovery="Re-run prepare with the correct batch row or repair the missing source batch first.",
        metadata_keys=("cluster",),
    ),
    "bura-md-workflow": DashboardActionContract(
        contract_id="bura-md-workflow",
        label="Run full BURA MD workflow",
        view="Dash Thesis Cockpit",
        trigger="Run MD workflow",
        action_kind="bura-md-workflow",
        approval="required",
        scope="bura",
        cluster="bura",
        writes=("local MD campaign directory", "remote BURA campaign", "dashboard action/sync state", "returned MD review artifacts"),
        prerequisites=("A peptide sequence is selected", "no duplicate/running MD state exists", "BURA profile is configured"),
        postcondition="The macro action prepares the local campaign, runs BURA autopilot, copies outputs back, and finalizes md_review.csv when successful.",
        safer_option="Use Dash preview only or legacy Streamlit Advanced controls if recovery/override is needed.",
        recovery="Inspect Advanced BURA action logs or legacy Streamlit Remote BURA recovery; do not resubmit duplicates blindly.",
        metadata_keys=("macro_kind", "backend_kind", "payload_version", "sequence", "md_profile", "campaign_dir", "payload"),
        output_suffixes=("md_review.csv",),
    ),
    "bura-upload-campaign": DashboardActionContract(
        contract_id="bura-upload-campaign",
        label="Upload campaign to BURA",
        view="MD Validation",
        trigger="Upload campaign to BURA",
        action_kind="bura-upload-campaign",
        approval="required",
        scope="bura",
        cluster="bura",
        writes=("remote BURA campaign root", "dashboard transfer tracking"),
        prerequisites=("A prepared local campaign exists", "BURA connectivity/profile is configured"),
        postcondition="The current campaign is staged remotely and tracked by the dashboard.",
        safer_option="Run the MD slate rehearsal if you only need to verify ladder sequencing/caps.",
        recovery="Use Transfers or Recovery center to reconcile staging mismatches before resubmitting.",
        metadata_keys=("remote_path", "target_key"),
    ),
    "bura-normalize-scripts": DashboardActionContract(
        contract_id="bura-normalize-scripts",
        label="Normalize uploaded BURA scripts",
        view="MD Validation",
        trigger="Start BURA pre-submit sequence",
        action_kind="bura-normalize-scripts",
        approval="required",
        scope="bura",
        cluster="bura",
        writes=("remote shell scripts in the staged campaign",),
        prerequisites=("The campaign is already uploaded to BURA",),
        postcondition="Uploaded shell scripts are normalized and executable for preflight/submit.",
        safer_option="Inspect the rehearsal ladder first if you only need process confidence, not a real remote submit chain.",
        recovery="Re-upload the campaign if normalization fails because the staged files are incomplete or stale.",
        metadata_keys=("remote_path", "target_key"),
    ),
    "bura-poll-squeue": DashboardActionContract(
        contract_id="bura-poll-squeue",
        label="Monitor active BURA campaign",
        view="MD Validation",
        trigger="Monitor active BURA campaign",
        action_kind="bura-poll-squeue",
        approval="not_required",
        scope="bura",
        cluster="bura",
        writes=("dashboard queue snapshot/logs only",),
        prerequisites=("A tracked BURA job id exists or the ladder is remotely active",),
        postcondition="The latest BURA queue state is captured and the ladder sync state can advance.",
        safer_option="None needed; this is a read-mostly monitoring action.",
        recovery="If the job no longer appears, open Operations -> Remote jobs and reconcile the remote state.",
        metadata_keys=("target_key", "remote_job_id"),
    ),
    "finalize-md-stage": DashboardActionContract(
        contract_id="finalize-md-stage",
        label="Finalize MD outputs locally",
        view="MD Validation",
        trigger="Finalize ...",
        action_kind="finalize-md-stage",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("md_review.csv", "parsed local ladder state"),
        prerequisites=("Copied-back outputs or staged outputs are present for the current campaign",),
        postcondition="The current rung is parsed into local review artifacts and the next ladder recommendation is refreshed.",
        safer_option="Use the rehearsal slate when you want to see end-state handoffs without parsing real outputs.",
        recovery="Use Artifact verification and Transfers to repair missing files before retrying finalize.",
        output_suffixes=("md_review.csv",),
    ),
    "make-md-ingest-csv": DashboardActionContract(
        contract_id="make-md-ingest-csv",
        label="Create ingest CSV from reviewed MD result",
        view="MD Validation",
        trigger="Create ingest CSV",
        action_kind="make-md-ingest-csv",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("cgmd_ingest.csv",),
        prerequisites=("A full-analysis campaign exists", "an evidence-backed human cgmd_label is already saved", "the result is ingest-supported"),
        postcondition="A real cgmd_ingest.csv exists for the evidence-backed reviewed campaign.",
        safer_option="Use the AL loop simulator to dry-run the ingest handoff without writing real import files.",
        recovery="If the result is reporting-only, promote it into a real proposed batch before retrying.",
        output_suffixes=("cgmd_ingest.csv",),
    ),
    "update-md-review": DashboardActionContract(
        contract_id="update-md-review",
        label="Save MD review decision locally",
        view="MD Validation",
        trigger="Save review locally",
        action_kind="update-md-review",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("md_review.csv",),
        prerequisites=("A returned full-analysis review row exists",),
        postcondition="The local md_review.csv captures the current human label, rubric, confidence, evidence summary, and notes.",
        safer_option="Use the AL loop simulator if you only want to rehearse the handoff instead of committing a real review row.",
        recovery="Edit the review row again if the label or notes need correction before ingest.",
        output_suffixes=("md_review.csv",),
    ),
    "export-md-source-batch": DashboardActionContract(
        contract_id="export-md-source-batch",
        label="Create dashboard-local MD source batch rows",
        view="Peptides",
        trigger="Create dashboard-local MD batch rows",
        action_kind="export-md-source-batch",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("dashboard-local MD source batch CSV",),
        prerequisites=("At least one candidate sequence is selected",),
        postcondition="The chosen candidates gain a dashboard-local source batch row so they become MD-launchable for reporting/rehearsal flows.",
        safer_option="None needed; this action is already local-only and non-destructive.",
        recovery="Delete or ignore the dashboard-local batch rows if you later decide the candidate should not move toward MD.",
    ),
    "promote-reporting-md-campaign": DashboardActionContract(
        contract_id="promote-reporting-md-campaign",
        label="Promote reporting-only MD result into real AL batch",
        view="MD Validation",
        trigger="Promote into real AL batch",
        action_kind="promote-reporting-md-campaign",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("manifest.csv", "md_review.csv", "md_stage_meta.json"),
        prerequisites=("A real proposed batch now contains the peptide", "the reviewed campaign already exists"),
        postcondition="The campaign points to a real proposed batch row and can become genuinely ingest-ready.",
        safer_option="If you only need thesis evidence, keep the campaign reporting-only and do not promote it yet.",
        recovery="Rebuild the ingest CSV after promotion; stale ingest files are intentionally removed during promotion.",
    ),
    "continue-al-feedback": DashboardActionContract(
        contract_id="continue-al-feedback",
        label="Continue AL from reviewed peptides",
        view="Model Workflow",
        trigger="Continue AL from reviewed peptides",
        action_kind="continue-al-feedback",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("aggregate feedback import CSV", "training outputs", "updated metrics", "optional next batch"),
        prerequisites=("The entire pending proposed batch is reviewed and ready",),
        postcondition="The active-learning loop closes on the reviewed batch and the run is ready for the next thesis/model step.",
        safer_option="Use the AL loop simulator to inspect the same ingest/retrain/propose chain without touching the run.",
        recovery="Open Model Workflow -> feedback queue to see which peptide still blocks the loop if the action cannot proceed.",
    ),
    "ingest-round": DashboardActionContract(
        contract_id="ingest-round",
        label="Ingest returned labels",
        view="Model Workflow",
        trigger="Ingest returned labels",
        action_kind="ingest-round",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("run imports", "training outputs", "updated metrics"),
        prerequisites=("A reviewed ingest CSV already exists",),
        postcondition="The newest returned labels are imported and the local model state is retrained/evaluated.",
        safer_option="Use the AL loop simulator to dry-run the ingest/retrain handoff first.",
        recovery="Rebuild or correct the ingest CSV if the model ingest refuses the batch.",
    ),
    "propose-round": DashboardActionContract(
        contract_id="propose-round",
        label="Propose next peptide batch",
        view="Model Workflow",
        trigger="Propose next batch",
        action_kind="propose-round",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("next round batch CSV", "proposal artifacts"),
        prerequisites=("The run has a trained model state ready to propose from",),
        postcondition="A new proposed batch exists for the next round of MD selection.",
        safer_option="Use the AL loop simulator if you only want to preview next-round readiness.",
        recovery="Re-run after fixing missing model artifacts or after completing the prior feedback loop.",
    ),
    "run-discovery": DashboardActionContract(
        contract_id="run-discovery",
        label="Run discovery",
        view="Model Workflow",
        trigger="Run discovery",
        action_kind="run-discovery",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("discovery summaries", "discovery exports"),
        prerequisites=("The run is mature enough for exploration",),
        postcondition="Discovery artifacts are refreshed for thesis exploration/reporting.",
        safer_option="Use the thesis results/reporting views if you only need to inspect existing discovery outputs.",
        recovery="Review model readiness and prior imports if discovery cannot start.",
    ),
    "evaluate-final": DashboardActionContract(
        contract_id="evaluate-final",
        label="Run frozen holdout evaluation",
        view="Model Workflow",
        trigger="Run frozen holdout evaluation",
        action_kind="evaluate-final",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("final holdout metrics",),
        prerequisites=("The run is at a reportable checkpoint",),
        postcondition="Final evaluation metrics are updated for thesis reporting.",
        safer_option="Inspect current Results views first if you only need already-exported evidence.",
        recovery="Re-run after fixing the trained model or holdout artifact prerequisites.",
    ),
    "freeze-final": DashboardActionContract(
        contract_id="freeze-final",
        label="Freeze final thesis result",
        view="Model Workflow",
        trigger="Freeze final thesis result",
        action_kind="freeze-final",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("final freeze manifest", "freeze checks", "model manifest", "model card"),
        prerequisites=("Final holdout metrics exist, or Run final evaluation first is enabled",),
        postcondition="The selected run has a final_freeze bundle that can be cited for thesis reporting.",
        safer_option="Run Final evaluation first if you only need metrics and are not ready to freeze reproducibility artifacts.",
        recovery="Use --force from the GUI only when you intentionally want to replace an existing freeze.",
    ),
    "export-thesis-packet": DashboardActionContract(
        contract_id="export-thesis-packet",
        label="Export thesis packet",
        view="Results",
        trigger="Export thesis packet",
        action_kind="export-thesis-packet",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("packet README", "packet manifest", "thesis evidence tables", "reproducibility metadata"),
        prerequisites=("At least one run is visible under the selected run root",),
        postcondition="A timestamped thesis packet exists under _thesis_packets or the chosen output directory.",
        safer_option="Use the read-only Results tables if you only need to inspect evidence without writing an export bundle.",
        recovery="Export again with a clearer title, or ignore the older packet if it was only a draft.",
    ),
    "build-thesis-figures": DashboardActionContract(
        contract_id="build-thesis-figures",
        label="Build thesis figures",
        view="Results",
        trigger="Build figures from selected packet",
        action_kind="build-thesis-figures",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("SVG figures", "clean table CSVs", "caption markdown", "figure manifest"),
        prerequisites=("A thesis packet directory with packet_manifest.json exists",),
        postcondition="The chosen packet has an output-only thesis_figures bundle.",
        safer_option="Export a fresh thesis packet first if the selected packet is stale.",
        recovery="Delete or ignore the figure bundle and rebuild after exporting a newer packet.",
    ),
    "thesis-canary": DashboardActionContract(
        contract_id="thesis-canary",
        label="Run seeded thesis canary",
        view="Results",
        trigger="Run seeded thesis canary",
        action_kind="thesis-canary",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("synthetic canary run", "canary report JSON", "canary report markdown"),
        prerequisites=("The run root is writable",),
        postcondition="A deterministic synthetic end-to-end canary report exists under _thesis_canaries.",
        safer_option="Skip this if you only need real-run reporting outputs; the canary is a confidence check.",
        recovery="Rerun with Force enabled when replacing the same canary name and seed is intentional.",
    ),
    "init-run": DashboardActionContract(
        contract_id="init-run",
        label="Create new thesis run",
        view="Operations",
        trigger="Create run from wizard",
        action_kind="init-run",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("new run directory", "config.json", "split manifest", "ledger", "baseline model", "optional replay outputs", "optional curation pin/label"),
        prerequisites=("The chosen run folder name does not already exist", "The run root is writable"),
        postcondition="A new run exists and is ready to continue from Model Workflow.",
        safer_option="Use the Quick smoke preset when you only want to confirm the setup path before a real thesis run.",
        recovery="If the setup fails, inspect the action logs, choose a new run name if partial files exist, then relaunch.",
    ),
    "run-study": DashboardActionContract(
        contract_id="run-study",
        label="Run study / ablation",
        view="Operations",
        trigger="Run study from designer",
        action_kind="run-study",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("study manifest", "per-seed run directories", "replay outputs", "study evidence tables"),
        prerequisites=("The study name is unique or intentionally resumable", "The run root is writable"),
        postcondition="A study manifest and replay evidence exist for the requested seeds/strategies.",
        safer_option="Enable Dry run first to write only the study plan without launching model training.",
        recovery="Resume the same study with allow-config-mismatch only if you intentionally accept existing run configs.",
    ),
    "summarize-study": DashboardActionContract(
        contract_id="summarize-study",
        label="Summarize study evidence",
        view="Operations",
        trigger="Summarize replay evidence",
        action_kind="summarize-study",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("study summary JSON", "strategy summary CSV", "run/strategy summary CSV", "paired-vs-random CSV"),
        prerequisites=("Replay summaries exist under the selected run root",),
        postcondition="Thesis-ready study evidence tables exist for the selected metric.",
        safer_option="Use Results -> Study comparison hub to inspect existing summaries before regenerating.",
        recovery="Regenerate the summary after fixing missing replay artifacts or narrowing the selected run set.",
    ),
    "compare-studies": DashboardActionContract(
        contract_id="compare-studies",
        label="Compare two studies",
        view="Operations",
        trigger="Compare matched studies",
        action_kind="compare-studies",
        approval="not_required",
        scope="local",
        cluster="",
        writes=("paired comparison CSV", "strategy delta CSV", "comparison summary JSON", "thesis narrative markdown"),
        prerequisites=("Two study manifests share matched seeds/strategies",),
        postcondition="A matched comparison bundle exists under _studies/_comparisons.",
        safer_option="Summarize each study first and check that seeds/strategies match.",
        recovery="If no pairs match, rerun one study with matching seed/strategy settings or compare different manifests.",
    ),
    "supek-sync-run": DashboardActionContract(
        contract_id="supek-sync-run",
        label="Stage run on SUPEK",
        view="Model Workflow",
        trigger="Stage this run on SUPEK",
        action_kind="supek-sync-run",
        approval="required",
        scope="supek",
        cluster="supek",
        writes=("dashboard-local upload staging", "remote SUPEK scratch run directory"),
        prerequisites=("The run exists locally", "SUPEK profile/connectivity is configured"),
        postcondition="A staged remote run directory exists and is tracked by the dashboard.",
        safer_option="Use the local workflow runner if the next step does not need SUPEK yet.",
        recovery="Use Transfers and Remote jobs if staging partially succeeds or drift appears.",
        metadata_keys=("remote_path", "target_key", "local_stage_path"),
    ),
    "supek-submit-workflow": DashboardActionContract(
        contract_id="supek-submit-workflow",
        label="Submit workflow on SUPEK",
        view="Model Workflow",
        trigger="Submit next SUPEK workflow",
        action_kind="supek-submit-workflow",
        approval="required",
        scope="supek",
        cluster="supek",
        writes=("remote PBS wrapper/log paths", "tracked remote job metadata"),
        prerequisites=("The run is already staged on SUPEK", "the next remote workflow is known"),
        postcondition="An approval-gated remote workflow draft exists with tracked job/log metadata.",
        safer_option="Run the local workflow action instead if you do not need remote execution.",
        recovery="Use SUPEK preflight, queue polling, and log fetch before resubmitting.",
        metadata_keys=("remote_path", "remote_stdout", "remote_stderr", "remote_wrapper", "workflow_command", "target_key"),
    ),
    "supek-submit-study": DashboardActionContract(
        contract_id="supek-submit-study",
        label="Submit study on SUPEK",
        view="Operations",
        trigger="Draft SUPEK study job from Study designer",
        action_kind="supek-submit-study",
        approval="required",
        scope="supek",
        cluster="supek",
        writes=("remote PBS wrapper/log paths", "remote study run root", "tracked remote job metadata"),
        prerequisites=("The study dry-run plan has been reviewed", "SUPEK profile/connectivity is configured", "walltime is appropriate for the seed count"),
        postcondition="An approval-gated remote study draft exists and can submit the multi-seed study to SUPEK.",
        safer_option="Keep Dry run enabled first, or use the local dry-run action before spending SUPEK compute.",
        recovery="Use Operations -> Remote jobs to poll/fetch logs; if the job times out, resubmit the same study with a longer walltime because run-study is resumable.",
        metadata_keys=("study_name", "remote_path", "remote_stdout", "remote_stderr", "remote_wrapper", "walltime", "target_key"),
    ),
    "supek-submit-study-array": DashboardActionContract(
        contract_id="supek-submit-study-array",
        label="Submit split study on SUPEK",
        view="Operations",
        trigger="Draft split SUPEK study jobs from Study designer",
        action_kind="supek-submit-study-array",
        approval="required",
        scope="supek",
        cluster="supek",
        writes=("remote per-seed PBS wrappers/log paths", "remote aggregate PBS wrapper/log paths", "tracked remote job metadata"),
        prerequisites=("The study dry-run plan has been reviewed", "SUPEK profile/connectivity is configured", "walltime is appropriate for one seed job"),
        postcondition="Approval submits one SUPEK job per seed and one aggregate job that depends on all seed jobs.",
        safer_option="Use single-job SUPEK submission if queue slot pressure matters more than timeout safety.",
        recovery="If one seed fails, inspect its seed-specific logs, rerun the split study after fixing the issue, then the aggregate job can rebuild the manifest from completed run folders.",
        metadata_keys=("study_name", "remote_path", "remote_stdout", "remote_stderr", "remote_wrapper", "seed_job_count", "walltime", "aggregate_walltime", "target_key"),
    ),
    "supek-poll-qstat": DashboardActionContract(
        contract_id="supek-poll-qstat",
        label="Monitor current SUPEK job",
        view="Model Workflow",
        trigger="Monitor current SUPEK job",
        action_kind="supek-poll-qstat",
        approval="not_required",
        scope="supek",
        cluster="supek",
        writes=("dashboard queue snapshot/logs only",),
        prerequisites=("A tracked SUPEK job id exists",),
        postcondition="The latest SUPEK queue state is captured and remote sync can refresh.",
        safer_option="None needed; this is a monitoring action.",
        recovery="If the job disappeared, fetch logs or reconcile the remote state before relaunching anything.",
        metadata_keys=("target_key", "remote_job_id"),
    ),
    "al-loop-simulation": DashboardActionContract(
        contract_id="al-loop-simulation",
        label="Start AL loop rehearsal",
        view="Operations",
        trigger="Start loop rehearsal",
        action_kind=None,
        approval="not_applicable",
        scope="local",
        cluster="",
        writes=("dashboard-local AL loop simulation state", "dashboard-local MD rehearsal state"),
        prerequisites=("At least one launch-ready candidate is visible for the chosen run",),
        postcondition="A local-only rehearsal exists for candidate -> MD -> review -> ingest -> retrain/propose.",
        safer_option="This action is itself the safe rehearsal path.",
        recovery="Restart the rehearsal or inject labels/ingest steps again; no real run files are modified.",
        mode="local_only",
    ),
}


def list_dashboard_action_contracts() -> list[DashboardActionContract]:
    return list(DASHBOARD_ACTION_CONTRACTS.values())


def get_dashboard_action_contract(contract_id: str) -> DashboardActionContract | None:
    return DASHBOARD_ACTION_CONTRACTS.get(str(contract_id).strip())


def validate_dashboard_action_contract(action: dict[str, object], contract_id: str) -> list[str]:
    contract = get_dashboard_action_contract(contract_id)
    if contract is None:
        return [f"Unknown dashboard action contract: {contract_id}"]
    if contract.mode != "action":
        return [f"Contract {contract_id} is local-only and should not be validated against a dashboard action."]
    problems: list[str] = []
    if str(action.get("kind", "")) != str(contract.action_kind or ""):
        problems.append(f"expected kind={contract.action_kind}, got {action.get('kind', '')}")
    approval_expected = contract.approval == "required"
    metadata = action.get("metadata", {}) if isinstance(action.get("metadata", {}), dict) else {}
    trusted_inline_approval = bool(metadata.get("trusted_inline_approval", False))
    if bool(action.get("requires_approval", False)) != approval_expected and not (
        approval_expected and trusted_inline_approval
    ):
        problems.append(
            f"expected requires_approval={approval_expected}, got {bool(action.get('requires_approval', False))}"
        )
    if str(action.get("scope", "")) != contract.scope:
        problems.append(f"expected scope={contract.scope}, got {action.get('scope', '')}")
    expected_cluster = contract.cluster.strip()
    actual_cluster = str(action.get("cluster", "")).strip()
    if expected_cluster != actual_cluster:
        problems.append(f"expected cluster={expected_cluster or '<none>'}, got {actual_cluster or '<none>'}")
    if contract.output_suffixes:
        output_path = str(action.get("output_path", "")).replace("\\", "/")
        if not any(output_path.endswith(suffix.replace("\\", "/")) for suffix in contract.output_suffixes):
            problems.append(f"expected output_path to end with one of {contract.output_suffixes}, got {action.get('output_path', '')}")
    metadata = action.get("metadata", {}) if isinstance(action.get("metadata", {}), dict) else {}
    for key in contract.metadata_keys:
        if key not in metadata:
            problems.append(f"missing metadata key: {key}")
    return problems
